version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  fastapi:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: fastapi
    restart: always
    env_file: .env
    ports:
      - 8000:80
    depends_on:
      - postgres
    volumes:
      - .:/backend-developer-test
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

volumes:
  postgres_data: